//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kimathi_Construction
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public int IdNum { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public string TypeOfEmployee { get; set; }
    
        public virtual Work Work { get; set; }
    }
}
