//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kimathi_Construction
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int Id { get; set; }
        public string RawMaterial { get; set; }
        public Nullable<int> AmountIn { get; set; }
        public Nullable<int> AmountOut { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
