//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kimathi_Construction
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public long IdNum_fk { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
